# 1. Numpy 
Numpy is a powerful Python module that should be in the toolbelt of any AI/Deep learning practitioner. It provides functions and data strutctures that allow fast, efficient manipulation of mathematical structures like matrices and vectors. It represents these structures internally using Numpy arrays, which are like Python Lists, but highly optimised for calculations on large amounts of numerical data. Let's import this module now.

In [1]:
import numpy as np

### 1.1.1 Array creation
Numpy arrays can be created in a few different ways. Common ones are:
1. Instantiated using values from a normal Python list
2. Filled with sequential values upto a target number
3. Filled with a specific value
4. Filled with random values (various random distributions available) - see https://numpy.org/doc/stable/reference/random/index.html

For a full list of array creation routines, please see: https://numpy.org/doc/stable/reference/routines.array-creation.html


In [2]:
#Array creation from python list
python_list = [2, 4, 8, 16, 32, 64, 128, 256, 512, 1024]
np_from_list = np.array(python_list)  
print(np_from_list)

[   2    4    8   16   32   64  128  256  512 1024]


In [3]:
# Array creation with sequential values 
# arange always returns a 1D array, will need to reshape it separately if
# we wish to do so
seq_array = np.arange(20)
print(seq_array)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [4]:
#Array creation with random values 
random_array = np.random.rand(10)  # returns an array filled with 10 random floats between 0 and 1
print(random_array)

[0.54055071 0.008152   0.56317885 0.84962779 0.10039291 0.58032141
 0.14445078 0.89859919 0.62883073 0.18385217]


In [5]:
#Array filled with the same specific value
filled_array = np.full(10, 256)  # returns an array filled with 10 instances of 256
print(filled_array)

[256 256 256 256 256 256 256 256 256 256]


### 1.1.2 Reshaping arrays

One of the many things that set Numpy arrays apart from Python lists is their `reshape` method. This allows you to define the number of dimensions that the structure represented by the array has. For example, the array `np_from_list` that we have just defined is just a flat list of numbers at the moment. `reshape` helps us represent it as a 2D data structure (a matrix). Keep in mind that the shape that you put into this method must agree with the number of elements in the array. In our example, the array has 10 elements, so acceptable shapes include:
* 5, 2
* 2, 5
* 1, 10
* 10, 1

In [6]:
matrix_5_2 = np_from_list.reshape(5,2)
print(matrix_5_2)
print(f"matrix_5_2 shape: {matrix_5_2.shape}")

[[   2    4]
 [   8   16]
 [  32   64]
 [ 128  256]
 [ 512 1024]]
matrix_5_2 shape: (5, 2)


In [7]:
matrix_2_10 = seq_array.reshape(2,10)
print(matrix_2_10)
print(f"matrix_2_10 shape: {matrix_2_10.shape}")

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]
matrix_2_10 shape: (2, 10)


In [14]:
# You can also pass a desired shape into the array creation function to instantiate
# an array with a pre-defined shape
array_from_shape = np.full(matrix_5_2.shape, 32)
array_from_shape

array([[0.09645619, 0.67159924],
       [0.74068637, 0.34299109],
       [0.31642837, 0.97169424],
       [0.94350288, 0.77766788],
       [0.01909443, 0.94197917]])

### 1.1.3 Exercises

In [ ]:
# Create a Numpy array A that contains the integers from 0 - 31 (32 elements long)
A = np.arange(32)
print(A)

In [ ]:
# Create a Numpy array B that contains 12 random numbers between 0 and 1
B = np.random.rand(12)
print(B)

In [ ]:
# Turn A into a 2d matrix of shape (8, 4) - 8 rows, 4 columns
A = A.reshape(8, 4)
print(A)

In [ ]:
# Turn B into a 2d matrix of shape (4, 3)
B = B.reshape(4, 3)
print(B)

## 1.2 Array operations
Once you have created an array, there are various operations you may want to perform on them. We'll go through some of the most common ones in the next few cells.

### 1.2.1 Binary operators
Similar to normal counting numbers, Numpy arrays can be used as arguments to binary arithmetic operators like `*` (multiplication), `+` (addition), `-`(subtraction) and `/`(division). However, these can only be applied to arrays under certain conditions:
1. The arrays have the same shape, OR
2. The operation is between an array and a scalar, OR
3. The operations is between 2 arrays of different shapes that can be "broadcast" together - more on this later

These operations are applied **element-wise** meaning each element in the array is combined with its corresponding element at the same position in the other array

In [ ]:
# Addition with a scalar
arr = np.random.rand(32).reshape(A.shape)
scalar_add_array = 11 + arr 
print(scalar_add_array)

In [ ]:
# Subtraction with another array of same shape
sub_array = arr - A 
print(sub_array)

In [ ]:
# Multiplication with another array of same shape
mul_array = arr * A 
print(mul_array)

In [ ]:
# Division by a scalar
div_array = 11 / arr 
print(div_array)

### 1.2.2 Broadcasting
As long as an array's dimensions are compatible with their counterparts in the other array, they can be "broadcasted" together. This means that numpy will 'strectch' the smaller dimension along its axis so that element-wise operations can be applied between them. In general, 2 arrays can be broadcast together if each dimension in one array is compatible with its counterpart in the other array. Dimensions are compatible if they are equal or one of them is equal to 1. The dimension of size 1 is expanded to fit the size of its counterpart [https://numpy.org/doc/stable/user/basics.broadcasting.html]

In [ ]:
array_4_1 = np.arange(4).reshape(4,1)
print(array_4_1, array_4_1.shape)  

# array_4_1 has shape (4, 1) so it can be broadcast to shape (4, 3) along B's horizontal axis
# it's as if array_4_1 has been copied along the horizontal axis so that it can be added to B
broadcasted = array_4_1 + B
print(broadcasted, broadcasted.shape)

In [ ]:
# Similarly, we can also broadcast an array of shape (1, 2) along B's vertical axis
array_1_3 = np.arange(3).reshape(1,3)
print(array_1_3, array_1_3.shape)

broadcasted = array_1_3 * B
print(broadcasted, broadcasted.shape)




### 1.2.3 Array products
Contrary to the `*` operator, which performs element-wise multiplication between the arrays, `np.matmul` is the matrix product of the arrays.

In [ ]:
matmul_matrix = np.matmul(A, B)
print(f"A shape: {A.shape}, B shape: {B.shape}, AB shape: {matmul_matrix.shape}")

### 1.2.4 Exercises

In [ ]:
# Divide your array B by the number 2.5. Store the result in a variable C
C = B / 2.5
print(C)

In [ ]:
# Create a new array filled with -1. The array must have the same shape as B. Store the result in a variable D
D = np.full(12, -1).reshape(B.shape)
print(D)

In [ ]:
# Multiply this new array ELEMENT-WISE with B and store the result in a variable called E.
E = D * C
print(E)

In [ ]:
# Consider the intermediate array below. Try and multiply it with D element-wise. What happens?
intermediate_arr = np.arange(4).reshape(2, 2)
print(intermediate_arr)

In [ ]:
# What could you do to make this multiplication work? (hint: try and make the intermediate array broadcastable to C)
intermediate_arr = intermediate_arr.reshape(4, 1)
F = E * intermediate_arr
print(F)

## 1.3 Functions
Another useful thing we might want to do with an array is to apply a function to each element. Generally speaking, it is best to use the built-in Numpy functions to work on numpy arrays instead of defining your own. This is because Numpy functions are highly optimised for speed, which is important when working with large amounts of data. Chances are, whatever kind of mathematical operation you want to perform on a Numpy array is already built in. See below for a full list:  
https://numpy.org/doc/stable/reference/routines.math.html  

### 1.3.1 Element-wise functions
Common uses are applying trig functions to an array of values:

In [ ]:
import matplotlib.pyplot as plt

def simple_plot(x, y, label):
    plt.plot(x, y)
    plt.suptitle(label)
    plt.show()

    

# Element-wise functions: 
G = np.arange(0, 2*np.pi, 0.2)
H = np.sin(G)
simple_plot(G, H, "sin(G)")

H_1 = np.exp(G)
simple_plot(G, H_1, "exp(G)")

### 1.3.2 Reduce functions
These are applied along the selected axis, consume all the elements and reduce the axis down to 1 element. If no axis is specified, the function is applied to the whole array, and reduces it to a scalar

In [ ]:
print(A)

I = A.max()
print(f"Maximum value in A: \n{I}")

I_2 = np.mean(A, axis=0, keepdims=True)  # keepdims is needed to preserve the original shape of the axis
print(f"Average of each column in A: \n{I_2}")

I_3 = A.min(axis=1, keepdims=True) 
print(f"Minimum value in each row in A: \n{I_3}")


### 1.3.3 Exercises


In [ ]:
# Have a look at the trigonometric functions listed in the official numpy documentation: https://numpy.org/doc/stable/reference/routines.math.html
# Pick any element-wise function that takes 1 argument and apply it to the following array. store the result in a variable called Ys
Xs = np.arange(-2*np.pi, 2*np.pi, 0.1)
Ys = np.arctan(Xs)
print(Ys)

In [ ]:
# Call our previously-defined simple plot function and display your result! Give the plot a suitable title
simple_plot(Xs, Ys, "sin(Xs)")

In [ ]:
# Use a suitable Numpy reduce function to find the maximum value of your function's result
max_val = np.max(Ys)
print(max_val)

## 1.4 numpy.where
This allows us to conditionally modify the elements of an array, which can be useful for tasks like thresholding or masking.

In [ ]:
big_image = np.arange(10*10).reshape(10,10)
big_image_thresh = np.where(big_image<50, 0, big_image)
big_image_thresh


### 1.4.1 Exercises


In [ ]:
# Create a Numpy array of shape (10, 5) and fill it with random values between 0 and 1. Store it in a variable called J
J = np.random.rand(10*5).reshape(10, 5)
print(J)

In [ ]:
# Conditionally modify the array such that numbers below 0.5 are replaced with 0 and numbers above or equal to 0.5 are replaced with 1. Store the result in a variable called K
K = np.where(J<0.5, 0, 1)
print(K)

## 1.5 Practical example

Putting everything together for a practical example, and visulalise the output of some Numpy operations

In [ ]:
# Defining some helper functions
def plot_point(point):
    plt.rcParams["figure.figsize"] = [3.50, 3.50]
    plt.rcParams["figure.autolayout"] = True
    x = point[0]
    y = point[1]
    
    lims = 3
    fig = plt.figure()
    ax = fig.add_subplot(111)
    plt.xlim(-lims, lims)
    plt.ylim(-lims, lims)
    plt.grid()
    ax.plot(x, y, marker="o", markersize=7, markeredgecolor="black", markerfacecolor="red")
    ax.spines['left'].set_position('zero')
    ax.spines['right'].set_color('none')
    ax.spines['bottom'].set_position('zero')
    ax.spines['top'].set_color('none')
    plt.show()



# This function returns an np array that describes a 2d rotation 
# matrix [https://www1.udel.edu/biology/rosewc/kaap686/notes/matrices_rotations.pdf]. 
# These kinds of structures are often used in computer graphics to rotate and translate points in space
def get_rot_clockwise_matrix(angle):
    return np.array([
        [ np.cos(angle), np.sin(angle)],
        [-np.sin(angle), np.cos(angle)]
    ])

In [ ]:
# Create a random 2-element array containing values from 0 - 1. Assign this array to a variable `p`
p = np.random.rand(2) 
print(p)

In [ ]:
# Using scalar multiplication to double the value of the elements in `p`. Assign the result back to `p`
p = 2 * p              # scale array 
print(p)

In [ ]:
# Reshape `p` to be (2, 1), assign the result to `p` and plot the point.
p = p.reshape(2, 1)    
plot_point(p)

In [ ]:
# We will now rotate this point about the origin of the plot using the funciton we defined above
# This cell is just some setup for the rest of the exercise, just run it once
min_angle = np.pi/2 # 90 degrees
max_angle = np.pi   # 180 degrees
angle = np.random.uniform(min_angle, max_angle) # get a random angle between 90 and 180 degrees
print(np.degrees(angle)) # print the angle in degrees so we can check the rotation is correct!

In [ ]:
# Call the previously-defined roation matrix function with the angle. Assign the result to 
# a variable called `rot90`
rot90 = get_rot_clockwise_matrix(angle)
print(rot90)

In [ ]:
# Apply a matrix multiplication operation between rot90 and p. assign the result back to p and plot it.
p = np.matmul(rot90, p)
plot_point(p)

In [ ]:
# Create an array named `translation` which has the same shape as `p`, and fill it with 2's
translation = np.full(p.shape, 2)
print(translation)

In [ ]:
# Add this result to p and plot it!
p = p + translation 
plot_point(p)